### PR TITLE
Add tidyr

### PR DESCRIPTION
**Pull request by WilDoane**
A first offering to partially address #22

### CODE REVIEW

**Comment by elbersb** [comment]
Hi, this looks great!

My only concern is that the messages printed are very long, so maybe we could brainstorm a bit and think about possible ways of keeping it shorter.

Right now it's this:

```
gather: was 32 rows and 12 columns; now 352 rows and 3 columns; reorganized data from (mpg, cyl, disp, hp, drat, …) into (col, data)
spread: was 352 rows and 3 columns, now 32 rows and 12 columns; reorganized data from (col, data) into (am, carb, cyl, disp, drat, …)
```

How about something like this? This also prints how many columns are actually involved?

```
gather: reorganized 11 columns (mpg, cyl, disp, hp, drat, …) into (col, data) [was 32x12, now 352x3]
spread: reorganized (col, data) into 11 columns (mpg, cyl, disp, hp, drat, …) [was 352x3, now 32x12]
```

**Comment by elbersb** [comment]
One other thing: Could you also build the package on your end so the .Rd files and the NAMESPACE files are updated? Thanks!

**Comment by WilDoane** [comment]
Done and done!

Example output:
```
> mtcars %>% mutate(id = 1:n()) %>% gather(col, data, -id) %>% spread(col, data) %>% head()
mutate: new variable 'id' with 32 unique values and 0% NA
gather: reorganized (mpg, cyl, disp, hp, drat, …) into (col, data) [was 32x12, now 352x3]
spread: reorganized (col, data) into (am, carb, cyl, disp, drat, …) [was 352x3, now 32x12]
```

**Comment by elbersb** [comment]
Great, I just merged this. `R CMD CHECK` gives an error, but I'll fix that.

**Pull request merged**
