### PR TITLE
Rd warnings when installing

### PR DESCRIPTION
**Pull request by bdsimpson**
Adjusted the @parm \link[dplyr] to \link[dplyr-inner_join] and \link[dplyr-transmute] to avoid installation warnings

### CODE REVIEW

**Comment by elbersb** [comment]
This gives warnings when running `R CMD CHECK`, though. (see Travis CI build)
```
* checking Rd cross-references ... WARNING
Unknown packages ‘dplyr-join’, ‘dplyr-transmute’ in Rd xrefs
```

Isn't this something that should be fixed in roxygen?

**Comment by elbersb** [comment]
I think this needs to be
`@param x a tbl; see \link[dplyr:join]{inner_join}`

i.e. colon instead of dash.

**Comment by bdsimpson** [comment]
You're absolutely correct - my box must have been acting funky
it needs @param x a tbl; see \link[dplyr:join]{inner_join}
and  
@param .data a tbl; see \link[dplyr:mutate]{transmute}   
    -or- 
@param .data a tbl; see \link[dplyr:mutate]{dplyr::transmute()}

Either of the transmute options work on my box, but the second one is recommend on SO

**Comment by elbersb** [comment]
whether it's `{transmute}` or `{dplyr::transmute()}` just affects the label of the link. Because everywhere else it's without the parentheses and the dplyr::, I'd prefer just {transmute}. Do you want to update the PR, or should I change this?

**Comment by bdsimpson** [comment]
I pulled a noob move and lost my original environment.  I opened a new PR that should have it fixed

**Pull request closed without merging**
